#!/bin/bash

# Ask the user for the name of the script
read -p "Enter the name of the script: " script_name
read -p "Enter pathname:" path

# Create the file with the given name and add a shebang line
touch "./$path/$script_name"
echo "#!/bin/bash" > "./$path/$script_name"

# Make the file executable
chmod +x "./$path/$script_name"

# Open the file in the default text editor
vi "./$path/$script_name"
